feat: forge-inspect all contracts
nomad-xyz/monorepo pull request #344
Opened 2022-06-14 08:46 UTC by odyslam

## Motivation

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Updated Documentation
- [ ] Updated CHANGELOG.md for the appropriate package

2022-06-21 15:10 UTC, prestwich commented on packages/contracts-core/scripts/storage-inspect.sh
> +echo -e "\nCurrent git commit $(git rev-parse HEAD) \n\n" >> $dir/../.storage-layout
ya, the changes are already associated with a commit. Let git manage exposing that info

2022-07-01 16:59 UTC, prestwich requested changes
add a CI step that generates these and fails CI if it generates a different file

2022-07-01 16:59 UTC, prestwich commented on packages/contracts-core/package.json
> +    "gen-sl": "scripts/storage-inspect.sh"
this should be added to the `build` script

2022-07-01 17:00 UTC, odyslam commented
Yeah. Let me add the bridge contracts as well and finally make an addition to the GitHub actions? 

We could have something like what was mentioned above. The test will fail if the storage has changed so the engineer has to explicitly acknowledge the change, create and commit the new storage layout so that the test doesn't fail, and then merge. What do you say?

2022-07-25 17:43 UTC, odyslam commented
Closing in favour of #403

2022-07-25 17:43 UTC, closed without merging